name: "Snapclient"
description: "Use your Home Assistant server as a Snapcast client"
version: "0.1.0"
slug: "snapclient"
init: false
audio: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  server_host: "127.0.0.1"
  server_port: 1704
  client_host_id: "hass"
schema:
  server_host: str
  server_port: int
  client_host_id: str
